import Navbar from "./components/navbar";
import Footer from "./components/footer";

import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>William Oktavianus</title>
        <meta
          name="description"
          content="This is William Oktavianus portfolio app."
        />
      </head>

      <body className="antialiased bg-background text-foreground flex flex-col min-h-screen">
        {/* Navigation Bar */}
        <Navbar />

        {/* Content */}
        <main className="flex-grow">{children}</main>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
